/* =============================================================================
   Todo en tus Manos — diccionarios.

   El español NO está aquí: está escrito en el HTML. Así la página se lee
   entera aunque el JS no cargue, y es lo que ve un buscador.

   Clave nueva ⇒ añadirla a LOS CUATRO diccionarios, no solo al inglés.
   ========================================================================== */

const IDIOMAS = {

  en: {
    'meta.titulo': 'All in Your Hands — Claude Code in your pocket',
    'nav.quees': 'What it is', 'nav.carac': 'Features', 'nav.seg': 'Security', 'nav.precios': 'Pricing', 'nav.cta': 'Request a quote',
    'hero.pildora': 'persistent session · tmux · 24/7',
    'hero.h1a': 'Claude Code,', 'hero.h1b': 'in your hands.',
    'hero.intro': "Anthropic's coding agent, running on your own server and driven from your phone. Close the app, lose signal, go grab lunch: Claude keeps working. When you come back, everything is right where you left it.",
    'hero.cta1': 'Request a quote', 'hero.cta2': 'See what it does',
    'hero.pie': 'Your server · your GitHub · your data. €9.99/month maintenance.',
    'datos.1': 'the session never sleeps', 'datos.2': 'languages in the app',
    'datos.3': 'data on other people’s servers', 'datos.4': 'per month, no lock-in',
    'sec.quees': 'How it works',
    'quees.h2': 'Three pieces, and all three are yours',
    'quees.bajada': 'Nothing passes through third-party servers. You own the entire circuit.',
    'pieza1.h3': 'Your server',
    'pieza1.p': 'A small cloud server you rent, in your name. That is where Claude Code lives and where your projects stay.',
    'pieza2.h3': 'Your phone',
    'pieza2.p': 'Open the app from your home screen, sign in with your face and talk to Claude as if you were texting a friend.',
    'pieza3.h3': 'Your GitHub',
    'pieza3.p': 'Every change is saved to your GitHub account: full history, mobile branches and automatic merging.',
    'sec.carac': 'Features',
    'carac.h2': 'Everything you need to code from your phone',
    'carac.bajada': 'Designed for one hand, anywhere, with zero terminal knowledge.',
    'c1.h3': 'A terminal that never sleeps',
    'c1.p': 'A persistent session on your server. Close the app or lose signal: Claude keeps working and everything is waiting when you return.',
    'c2.h3': 'Your face and two locks',
    'c2.p': 'Sign in with your face, or with a password plus a six-digit code that changes every thirty seconds. Two locks, one door.',
    'c3.h3': 'GitHub without the hassle',
    'c3.p': 'Clone projects from a dropdown, save and push on its own, and merge to main without typing a command.',
    'c4.h3': 'Connected to claude.ai',
    'c4.p': 'From the claude.ai chat you do not just read your code: you edit files, commit and push. Behind a switch that turns itself off.',
    'c5.h3': 'It updates itself',
    'c5.p': 'Every improvement reaches your server without you lifting a finger. Open the app and the latest version is already there.',
    'c6.h3': 'Built for your thumb, in 6 languages',
    'c6.p': 'Touch scrolling through the whole history, a box that mirrors what you type, and the whole app in six languages.',
    'sec.seg': 'Security',
    'seg.h2': 'Your data is yours. For real.',
    'seg.bajada': 'No accounts of ours in the middle, no shared servers: the server is yours and so are the keys.',
    's1.b': 'The key never leaves your phone',
    's1.p': 'Your secret key lives in the phone’s secure chip. The server never sees it and it cannot be stolen over the internet.',
    's2.b': 'Two-factor, always',
    's2.p': 'Even if someone guessed your password, without the six-digit code from your phone they do not get in. Period.',
    's3.b': 'Everything travels encrypted',
    's3.p': 'The connection between your phone and your server always runs over HTTPS with its own certificate, just like your bank.',
    's4.b': 'The server belongs to the client',
    's4.p': 'It is contracted in your name and only you hold the keys. Your code and your conversations pass through no one else.',
    'sec.precios': 'Pricing',
    'prec.h2': 'One payment to set it up, next to nothing per month',
    'prec.bajada': 'Separately you will need your own accounts: a paid Anthropic subscription (Pro is enough), GitHub — which is free — and a small server.',
    'plan1.h3': 'Full installation', 'plan1.cifra': 'Quote',
    'plan1.nota': 'One-off payment. We leave it running on your server and on your phone.',
    'plan1.l1': 'Installation on your server with HTTPS',
    'plan1.l2': 'Face sign-in, two-factor and GitHub configured',
    'plan1.l3': 'Guided setup on your phone',
    'plan1.l4': 'Printable installation guide included',
    'plan1.cta': 'Write to us',
    'plan2.cinta': 'maintenance', 'plan2.h3': 'Maintenance', 'plan2.mes': ' / month',
    'plan2.nota': 'You provide the server. We keep it up to date.',
    'plan2.l1': 'Automatic updates from GitHub',
    'plan2.l2': 'Improvements and new features included',
    'plan2.l3': 'Email support',
    'plan2.l4': 'Renews month by month, no lock-in',
    'plan2.cta': 'Get started',
    'plan3.cinta': 'most chosen',
    'plan3.h3': 'Server included',
    'plan3.mes': ' / month',
    'plan3.nota': 'Nothing to contract or configure: we provide the server.',
    'plan3.l1': 'Server included, in your name',
    'plan3.l2': 'All the maintenance of the previous plan',
    'plan3.l3': '1 hour a month with an expert, just for you',
    'plan3.l4': 'Renews month by month, no lock-in',
    'plan3.cta': 'Get started',
    'plan4.h3': 'With a dedicated expert',
    'plan4.mes': ' / month',
    'plan4.nota': 'For those who want to move fast and have someone on the other end.',
    'plan4.l1': 'Server and maintenance included',
    'plan4.l2': '3 hours a month with an expert, just for you',
    'plan4.l3': 'Explanations, programming and whatever you need',
    'plan4.l4': 'Renews month by month, no lock-in',
    'plan4.cta': 'Let\'s talk',
    'prec.guia': 'Prefer to set it up yourself? There is a step-by-step installation guide.',
    'prec.enlaceguia': 'See the installation guide',
    'sec.faq': 'Questions', 'faq.h2': 'What everyone asks',
    'f1.q': 'Do I need to know how to code?',
    'f1.a': 'No. You tell Claude what you want in your own words — "fix the button that does not respond", "add a contact page" — and it does the work. The app also includes a manual and the commands explained in plain language.',
    'f2.q': 'What if I close the app or lose signal?',
    'f2.a': 'Nothing bad. Claude works on your server, not on the phone. You can close the app, drive through a tunnel or switch the phone off: when you come back, the conversation and the work are exactly where they were.',
    'f3.q': 'Where are my projects stored?',
    'f3.a': 'On your own server, contracted in your name, with a backup in your GitHub account. We keep nothing of yours: we install the software and the keys stay with you.',
    'f4.q': 'What do I need to get started?',
    'f4.a': 'Three accounts: a paid Anthropic subscription (Pro, Max, Team or Enterprise; Pro is enough), a free GitHub account and a small server with a domain. With the full installation we do it for you.',
    'f5.q': 'Which Claude plans does it work with?',
    'f5.a': 'All four paid ones: Pro, Max, Team and Enterprise. It is the same Claude Code on all of them; the only difference is how much usage you get. Pro is enough to start.',
    'cierre.h2a': 'Your server. Your code.', 'cierre.h2b': 'Your pocket.',
    'cierre.p': 'Tell us what you want to set up and we will tell you what it takes, no strings attached.',
    'cierre.cta': 'Write to us',
    'pie.nota': 'Claude and Claude Code are trademarks of Anthropic. This product installs and manages Claude Code on your own server.'
  },

  fr: {
    'meta.titulo': 'Tout entre vos mains — Claude Code dans votre poche',
    'nav.quees': 'Ce que c’est', 'nav.carac': 'Fonctions', 'nav.seg': 'Sécurité', 'nav.precios': 'Tarifs', 'nav.cta': 'Demander un devis',
    'hero.pildora': 'session persistante · tmux · 24/7',
    'hero.h1a': 'Claude Code,', 'hero.h1b': 'entre vos mains.',
    'hero.intro': "L’agent de programmation d’Anthropic, sur votre propre serveur et piloté depuis votre téléphone. Fermez l’app, perdez le réseau, allez déjeuner : Claude continue. À votre retour, tout est là où vous l’aviez laissé.",
    'hero.cta1': 'Demander un devis', 'hero.cta2': 'Voir ce qu’il fait',
    'hero.pie': 'Votre serveur · votre GitHub · vos données. 9,99 €/mois de maintenance.',
    'datos.1': 'la session ne s’éteint jamais', 'datos.2': 'langues dans l’app',
    'datos.3': 'donnée sur des serveurs tiers', 'datos.4': 'par mois, sans engagement',
    'sec.quees': 'Comment ça marche',
    'quees.h2': 'Trois pièces, et les trois sont à vous',
    'quees.bajada': 'Rien ne passe par des serveurs tiers. Le circuit entier vous appartient.',
    'pieza1.h3': 'Votre serveur',
    'pieza1.p': 'Un petit serveur dans le cloud que vous louez, à votre nom. C’est là que vit Claude Code et que restent vos projets.',
    'pieza2.h3': 'Votre téléphone',
    'pieza2.p': 'Vous ouvrez l’app depuis l’écran d’accueil, vous entrez avec votre visage et vous parlez à Claude comme à un ami.',
    'pieza3.h3': 'Votre GitHub',
    'pieza3.p': 'Chaque changement est enregistré sur votre compte GitHub : historique complet, branches mobiles et fusion automatique.',
    'sec.carac': 'Fonctions',
    'carac.h2': 'Tout ce qu’il faut pour programmer depuis le téléphone',
    'carac.bajada': 'Pensé pour une seule main, n’importe où, sans rien connaître aux terminaux.',
    'c1.h3': 'Un terminal qui ne s’éteint jamais',
    'c1.p': 'Une session persistante sur votre serveur. Fermez l’app ou perdez le réseau : Claude continue et tout vous attend au retour.',
    'c2.h3': 'Votre visage et deux serrures',
    'c2.p': 'Entrez avec votre visage, ou avec un mot de passe plus un code à six chiffres qui change toutes les trente secondes.',
    'c3.h3': 'GitHub sans complications',
    'c3.p': 'Clonez des projets depuis une liste, enregistrez et envoyez tout seul, et fusionnez sans taper une commande.',
    'c4.h3': 'Connecté à claude.ai',
    'c4.p': 'Depuis le chat de claude.ai vous ne faites pas que lire votre code : vous modifiez, committez et envoyez. Derrière un interrupteur qui s’éteint seul.',
    'c5.h3': 'Il se met à jour tout seul',
    'c5.p': 'Chaque amélioration arrive sur votre serveur sans rien toucher. Vous ouvrez l’app et la dernière version est déjà là.',
    'c6.h3': 'Fait pour le pouce, en 6 langues',
    'c6.p': 'Défilement tactile dans tout l’historique, une boîte qui reflète ce que vous tapez, et toute l’app en six langues.',
    'sec.seg': 'Sécurité',
    'seg.h2': 'Vos données sont à vous. Vraiment.',
    'seg.bajada': 'Aucun compte à nous au milieu, aucun serveur partagé : le serveur est à vous, les clés aussi.',
    's1.b': 'La clé ne quitte pas le téléphone',
    's1.p': 'Votre clé secrète vit dans la puce sécurisée du téléphone. Le serveur ne la connaît pas et on ne peut pas la voler par internet.',
    's2.b': 'Double facteur, toujours',
    's2.p': 'Même si quelqu’un devinait votre mot de passe, sans le code à six chiffres de votre téléphone il n’entre pas. Point.',
    's3.b': 'Tout voyage chiffré',
    's3.p': 'La connexion entre votre téléphone et votre serveur passe toujours par HTTPS avec son propre certificat, comme votre banque.',
    's4.b': 'Le serveur appartient au client',
    's4.p': 'Il est souscrit à votre nom et vous seul avez les clés. Votre code et vos conversations ne passent par personne d’autre.',
    'sec.precios': 'Tarifs',
    'prec.h2': 'Un paiement pour la mise en route, presque rien par mois',
    'prec.bajada': 'À part, il vous faudra vos propres comptes : un abonnement payant Anthropic (Pro suffit), GitHub — gratuit — et un petit serveur.',
    'plan1.h3': 'Installation complète', 'plan1.cifra': 'Devis',
    'plan1.nota': 'Paiement unique. Nous vous le laissons en marche sur votre serveur et sur votre téléphone.',
    'plan1.l1': 'Installation sur votre serveur avec HTTPS',
    'plan1.l2': 'Visage, double facteur et GitHub configurés',
    'plan1.l3': 'Mise en route guidée sur votre téléphone',
    'plan1.l4': 'Guide d’installation imprimable inclus',
    'plan1.cta': 'Écrivez-nous',
    'plan2.cinta': 'maintenance', 'plan2.h3': 'Maintenance', 'plan2.mes': ' / mois',
    'plan2.nota': 'Vous fournissez le serveur. Nous le tenons à jour.',
    'plan2.l1': 'Mises à jour automatiques depuis GitHub',
    'plan2.l2': 'Améliorations et nouveautés incluses',
    'plan2.l3': 'Assistance par e-mail',
    'plan2.l4': 'Renouvelé mois par mois, sans engagement',
    'plan2.cta': 'Commencer',
    'plan3.cinta': 'le plus choisi',
    'plan3.h3': 'Serveur inclus',
    'plan3.mes': ' / mois',
    'plan3.nota': 'Rien à souscrire ni à configurer : le serveur, c’est nous.',
    'plan3.l1': 'Serveur inclus, à votre nom',
    'plan3.l2': 'Toute la maintenance de la formule précédente',
    'plan3.l3': '1 heure par mois avec un expert, rien que pour vous',
    'plan3.l4': 'Renouvelé mois par mois, sans engagement',
    'plan3.cta': 'Commencer',
    'plan4.h3': 'Avec expert dédié',
    'plan4.mes': ' / mois',
    'plan4.nota': 'Pour qui veut avancer vite et avoir quelqu’un en face.',
    'plan4.l1': 'Serveur et maintenance inclus',
    'plan4.l2': '3 heures par mois avec un expert, rien que pour vous',
    'plan4.l3': 'Explications, développement et ce qu’il vous faut',
    'plan4.l4': 'Renouvelé mois par mois, sans engagement',
    'plan4.cta': 'Parlons-en',
    'prec.guia': 'Vous préférez le monter vous-même ? Il y a un guide d’installation pas à pas.',
    'prec.enlaceguia': 'Voir le guide d’installation',
    'sec.faq': 'Questions', 'faq.h2': 'Ce que tout le monde demande',
    'f1.q': 'Faut-il savoir programmer ?',
    'f1.a': 'Non. Vous dites à Claude ce que vous voulez avec vos mots — « répare le bouton qui ne répond pas », « ajoute une page de contact » — et il fait le travail. L’app inclut aussi un manuel et les commandes expliquées simplement.',
    'f2.q': 'Et si je ferme l’app ou perds le réseau ?',
    'f2.a': 'Rien de grave. Claude travaille sur votre serveur, pas sur le téléphone. Vous pouvez fermer l’app, passer dans un tunnel ou éteindre le téléphone : au retour, la conversation et le travail sont exactement là où ils étaient.',
    'f3.q': 'Où sont stockés mes projets ?',
    'f3.a': 'Sur votre propre serveur, souscrit à votre nom, avec une copie sur votre compte GitHub. Nous ne gardons rien : nous installons le logiciel et les clés restent chez vous.',
    'f4.q': 'De quoi ai-je besoin pour commencer ?',
    'f4.a': 'Trois comptes : un abonnement payant Anthropic (Pro, Max, Team ou Enterprise ; Pro suffit), un compte GitHub gratuit et un petit serveur avec un domaine. Avec l’installation complète, nous le faisons pour vous.',
    'f5.q': 'Avec quels forfaits Claude cela fonctionne-t-il ?',
    'f5.a': 'Les quatre payants : Pro, Max, Team et Enterprise. C’est le même Claude Code partout ; seule la marge d’usage change. Pro suffit pour commencer.',
    'cierre.h2a': 'Votre serveur. Votre code.', 'cierre.h2b': 'Votre poche.',
    'cierre.p': 'Dites-nous ce que vous voulez monter et nous vous dirons ce qu’il faut, sans engagement.',
    'cierre.cta': 'Écrivez-nous',
    'pie.nota': 'Claude et Claude Code sont des marques d’Anthropic. Ce produit installe et gère Claude Code sur votre propre serveur.'
  },

  it: {
    'meta.titulo': 'Tutto nelle tue mani — Claude Code in tasca',
    'nav.quees': 'Cos’è', 'nav.carac': 'Funzioni', 'nav.seg': 'Sicurezza', 'nav.precios': 'Prezzi', 'nav.cta': 'Chiedi un preventivo',
    'hero.pildora': 'sessione persistente · tmux · 24/7',
    'hero.h1a': 'Claude Code,', 'hero.h1b': 'nelle tue mani.',
    'hero.intro': "L’agente di programmazione di Anthropic, sul tuo server e guidato dal telefono. Chiudi l’app, perdi il segnale, vai a pranzo: Claude continua a lavorare. Quando torni, è tutto dove l’avevi lasciato.",
    'hero.cta1': 'Chiedi un preventivo', 'hero.cta2': 'Vedi cosa fa',
    'hero.pie': 'Il tuo server · il tuo GitHub · i tuoi dati. 9,99 €/mese di manutenzione.',
    'datos.1': 'la sessione non si spegne mai', 'datos.2': 'lingue nell’app',
    'datos.3': 'dati su server altrui', 'datos.4': 'al mese, senza vincoli',
    'sec.quees': 'Come funziona',
    'quees.h2': 'Tre pezzi, e tutti e tre sono tuoi',
    'quees.bajada': 'Niente passa da server di terzi. Il circuito intero è di tua proprietà.',
    'pieza1.h3': 'Il tuo server',
    'pieza1.p': 'Un piccolo server nel cloud che affitti tu, a tuo nome. Lì vive Claude Code e lì restano i tuoi progetti.',
    'pieza2.h3': 'Il tuo telefono',
    'pieza2.p': 'Apri l’app dalla schermata iniziale, entri con il volto e parli con Claude come se scrivessi un messaggio.',
    'pieza3.h3': 'Il tuo GitHub',
    'pieza3.p': 'Ogni modifica finisce nel tuo account GitHub: cronologia completa, rami del telefono e unione automatica.',
    'sec.carac': 'Funzioni',
    'carac.h2': 'Tutto quello che serve per programmare dal telefono',
    'carac.bajada': 'Pensato per una mano sola, ovunque, senza sapere nulla di terminali.',
    'c1.h3': 'Un terminale che non si spegne mai',
    'c1.p': 'Sessione persistente sul tuo server. Chiudi l’app o perdi il segnale: Claude continua e tutto ti aspetta al ritorno.',
    'c2.h3': 'Il tuo volto e due serrature',
    'c2.p': 'Entri con il volto, oppure con password più un codice di sei cifre che cambia ogni trenta secondi.',
    'c3.h3': 'GitHub senza complicazioni',
    'c3.p': 'Cloni progetti da un elenco, salvi e carichi da solo, e unisci a main senza scrivere un comando.',
    'c4.h3': 'Collegato a claude.ai',
    'c4.p': 'Dalla chat di claude.ai non leggi soltanto il codice: modifichi file, fai commit e carichi. Dietro un interruttore che si spegne da solo.',
    'c5.h3': 'Si aggiorna da solo',
    'c5.p': 'Ogni miglioria arriva sul tuo server senza toccare niente. Apri l’app e c’è già l’ultima versione.',
    'c6.h3': 'Fatto per il pollice, in 6 lingue',
    'c6.p': 'Scorrimento tattile in tutta la cronologia, un riquadro che riflette ciò che scrivi, e l’app intera in sei lingue.',
    'sec.seg': 'Sicurezza',
    'seg.h2': 'I tuoi dati sono tuoi. Davvero.',
    'seg.bajada': 'Nessun account nostro di mezzo e nessun server condiviso: il server è tuo e anche le chiavi.',
    's1.b': 'La chiave non esce dal telefono',
    's1.p': 'La tua chiave segreta vive nel chip sicuro del telefono. Il server non la conosce e non si può rubare via internet.',
    's2.b': 'Doppio fattore, sempre',
    's2.p': 'Anche indovinando la password, senza il codice di sei cifre del tuo telefono non si entra. Punto.',
    's3.b': 'Tutto viaggia cifrato',
    's3.p': 'La connessione fra telefono e server passa sempre da HTTPS con certificato proprio, come la banca.',
    's4.b': 'Il server è del cliente',
    's4.p': 'È intestato a te e solo tu hai le chiavi. Il tuo codice e le tue conversazioni non passano da nessun altro.',
    'sec.precios': 'Prezzi',
    'prec.h2': 'Un pagamento per l’avvio, quasi niente al mese',
    'prec.bajada': 'A parte servono i tuoi account: un abbonamento a pagamento di Anthropic (basta il Pro), GitHub — gratuito — e un piccolo server.',
    'plan1.h3': 'Installazione completa', 'plan1.cifra': 'Preventivo',
    'plan1.nota': 'Pagamento unico. Te lo lasciamo funzionante sul tuo server e sul tuo telefono.',
    'plan1.l1': 'Installazione sul tuo server con HTTPS',
    'plan1.l2': 'Volto, doppio fattore e GitHub configurati',
    'plan1.l3': 'Avvio guidato sul tuo telefono',
    'plan1.l4': 'Guida di installazione stampabile inclusa',
    'plan1.cta': 'Scrivici',
    'plan2.cinta': 'manutenzione', 'plan2.h3': 'Manutenzione', 'plan2.mes': ' / mese',
    'plan2.nota': 'Il server lo metti tu. Noi lo teniamo aggiornato.',
    'plan2.l1': 'Aggiornamenti automatici da GitHub',
    'plan2.l2': 'Migliorie e funzioni nuove incluse',
    'plan2.l3': 'Assistenza via email',
    'plan2.l4': 'Si rinnova mese per mese, senza vincoli',
    'plan2.cta': 'Iniziare',
    'plan3.cinta': 'il più scelto',
    'plan3.h3': 'Server incluso',
    'plan3.mes': ' / mese',
    'plan3.nota': 'Niente da sottoscrivere né configurare: il server lo mettiamo noi.',
    'plan3.l1': 'Server incluso, a tuo nome',
    'plan3.l2': 'Tutta la manutenzione del piano precedente',
    'plan3.l3': '1 ora al mese con un esperto, solo per te',
    'plan3.l4': 'Si rinnova mese per mese, senza vincoli',
    'plan3.cta': 'Iniziare',
    'plan4.h3': 'Con esperto dedicato',
    'plan4.mes': ' / mese',
    'plan4.nota': 'Per chi vuole andare veloce e avere qualcuno dall’altra parte.',
    'plan4.l1': 'Server e manutenzione inclusi',
    'plan4.l2': '3 ore al mese con un esperto, solo per te',
    'plan4.l3': 'Spiegazioni, programmazione e quello che ti serve',
    'plan4.l4': 'Si rinnova mese per mese, senza vincoli',
    'plan4.cta': 'Parliamone',
    'prec.guia': 'Preferisci montarlo da solo? C’è una guida di installazione passo passo.',
    'prec.enlaceguia': 'Vedi la guida di installazione',
    'sec.faq': 'Domande', 'faq.h2': 'Quello che chiedono tutti',
    'f1.q': 'Devo saper programmare?',
    'f1.a': 'No. Dici a Claude cosa vuoi con parole tue — «sistema il pulsante che non risponde», «aggiungi una pagina contatti» — e lui fa il lavoro. L’app include anche un manuale e i comandi spiegati in modo semplice.',
    'f2.q': 'E se chiudo l’app o perdo il segnale?',
    'f2.a': 'Niente di grave. Claude lavora sul tuo server, non sul telefono. Puoi chiudere l’app, entrare in galleria o spegnere il telefono: al ritorno, conversazione e lavoro sono esattamente dov’erano.',
    'f3.q': 'Dove finiscono i miei progetti?',
    'f3.a': 'Sul tuo server, intestato a te, con copia nel tuo account GitHub. Noi non conserviamo nulla: installiamo il programma e le chiavi restano con te.',
    'f4.q': 'Cosa serve per iniziare?',
    'f4.a': 'Tre account: un abbonamento a pagamento di Anthropic (Pro, Max, Team o Enterprise; basta il Pro), un account GitHub gratuito e un piccolo server con un dominio. Con l’installazione completa lo facciamo noi.',
    'f5.q': 'Con quali piani di Claude funziona?',
    'f5.a': 'Con tutti e quattro quelli a pagamento: Pro, Max, Team ed Enterprise. È lo stesso Claude Code; cambia solo il margine di utilizzo. Il Pro basta per iniziare.',
    'cierre.h2a': 'Il tuo server. Il tuo codice.', 'cierre.h2b': 'La tua tasca.',
    'cierre.p': 'Raccontaci cosa vuoi montare e ti diciamo cosa serve, senza impegno.',
    'cierre.cta': 'Scrivici',
    'pie.nota': 'Claude e Claude Code sono marchi di Anthropic. Questo prodotto installa e gestisce Claude Code sul tuo server.'
  },

  zh: {
    'meta.titulo': '一切尽在你手 — 口袋里的 Claude Code',
    'nav.quees': '这是什么', 'nav.carac': '功能', 'nav.seg': '安全', 'nav.precios': '价格', 'nav.cta': '索取报价',
    'hero.pildora': '持久会话 · tmux · 全天候',
    'hero.h1a': 'Claude Code，', 'hero.h1b': '尽在你手。',
    'hero.intro': 'Anthropic 的编程助手，跑在你自己的服务器上，用手机操作。关掉 App、断网、去吃饭都没关系：Claude 会继续干活。回来时，一切都在你离开的地方。',
    'hero.cta1': '索取报价', 'hero.cta2': '看看它能做什么',
    'hero.pie': '你的服务器 · 你的 GitHub · 你的数据。维护费每月 9,99 €。',
    'datos.1': '会话永不关闭', 'datos.2': 'App 支持的语言',
    'datos.3': '数据留在别人服务器上', 'datos.4': '每月，无合约绑定',
    'sec.quees': '怎么运作',
    'quees.h2': '三个部分，三个都是你的',
    'quees.bajada': '不经过任何第三方服务器。整条链路都归你所有。',
    'pieza1.h3': '你的服务器',
    'pieza1.p': '一台你自己以本人名义租用的小型云服务器。Claude Code 住在那里，你的项目也留在那里。',
    'pieza2.h3': '你的手机',
    'pieza2.p': '从主屏幕打开 App，用面容登录，然后像发消息一样跟 Claude 说话。',
    'pieza3.h3': '你的 GitHub',
    'pieza3.p': '每一次改动都会保存到你的 GitHub 账号：完整历史、手机分支和自动合并。',
    'sec.carac': '功能',
    'carac.h2': '在手机上写代码所需要的一切',
    'carac.bajada': '为单手操作而设计，随时随地，不需要懂终端。',
    'c1.h3': '永不关闭的终端',
    'c1.p': '会话常驻在你的服务器上。关掉 App 或者断网都行：Claude 继续干，回来时一切都在等你。',
    'c2.h3': '面容加双重锁',
    'c2.p': '用面容登录，或者用密码加一个每三十秒变化一次的六位验证码。一扇门，两把锁。',
    'c3.h3': '省心的 GitHub',
    'c3.p': '从下拉列表克隆项目，自动保存并上传，不用敲一条命令就能合并到 main。',
    'c4.h3': '与 claude.ai 相连',
    'c4.p': '在 claude.ai 的对话里不只是查看代码：还能改文件、提交并上传。而且有一个会自动关闭的写入开关。',
    'c5.h3': '自动更新',
    'c5.p': '每一次改进都会自动到达你的服务器。打开 App，最新版本已经在那儿了。',
    'c6.h3': '为拇指打造，支持 6 种语言',
    'c6.p': '整个历史都能触摸滚动，有一个方框会显示你正在输入的内容，整个 App 支持六种语言。',
    'sec.seg': '安全',
    'seg.h2': '你的数据就是你的。真的。',
    'seg.bajada': '中间没有我们的账号，也没有共享服务器：服务器是你的，钥匙也是你的。',
    's1.b': '密钥不离开手机',
    's1.p': '你的密钥存在手机的安全芯片里。服务器不知道它，也无法通过网络被窃取。',
    's2.b': '始终双重验证',
    's2.p': '就算有人猜到你的密码，没有你手机上的六位验证码也进不来。就这么简单。',
    's3.b': '全程加密传输',
    's3.p': '手机和服务器之间始终走 HTTPS，用你自己的证书，和银行网站一样。',
    's4.b': '服务器属于客户',
    's4.p': '以你的名义签约，只有你握有密钥。你的代码和对话不经过任何人。',
    'sec.precios': '价格',
    'prec.h2': '一次性安装费，每月几乎不花钱',
    'prec.bajada': '另外你需要自己的账号：Anthropic 的付费订阅（Pro 就够了）、免费的 GitHub，以及一台小服务器。',
    'plan1.h3': '完整安装', 'plan1.cifra': '报价',
    'plan1.nota': '一次性付款。我们把它装好，在你的服务器和手机上跑起来。',
    'plan1.l1': '在你的服务器上安装并配置 HTTPS',
    'plan1.l2': '配置好面容登录、双重验证和 GitHub',
    'plan1.l3': '在你手机上引导完成启用',
    'plan1.l4': '附赠可打印的安装指南',
    'plan1.cta': '联系我们',
    'plan2.cinta': '维护', 'plan2.h3': '维护', 'plan2.mes': ' / 每月',
    'plan2.nota': '服务器由你提供，我们负责保持更新。',
    'plan2.l1': '从 GitHub 自动更新',
    'plan2.l2': '包含改进和新功能',
    'plan2.l3': '邮件支持',
    'plan2.l4': '按月续订，随时可停',
    'plan2.cta': '开始使用',
    'plan3.cinta': '最多人选',
    'plan3.h3': '含服务器',
    'plan3.mes': ' / 每月',
    'plan3.nota': '不用自己签约，也不用配置：服务器由我们提供。',
    'plan3.l1': '含服务器，以你的名义',
    'plan3.l2': '包含上一档的全部维护',
    'plan3.l3': '每月 1 小时专属专家时间',
    'plan3.l4': '按月续订，随时可停',
    'plan3.cta': '开始使用',
    'plan4.h3': '含专属专家',
    'plan4.mes': ' / 每月',
    'plan4.nota': '给想真正推进、并且希望随时有人对接的你。',
    'plan4.l1': '含服务器与维护',
    'plan4.l2': '每月 3 小时专属专家时间',
    'plan4.l3': '讲解、编程，以及你需要的任何事',
    'plan4.l4': '按月续订，随时可停',
    'plan4.cta': '聊一聊',
    'prec.guia': '想自己动手？这里有一份分步安装指南。',
    'prec.enlaceguia': '查看安装指南',
    'sec.faq': '常见问题', 'faq.h2': '大家都会问的',
    'f1.q': '我需要会编程吗？',
    'f1.a': '不需要。你用自己的话告诉 Claude 想要什么——「修一下没反应的按钮」「加一个联系页面」——它就去做。App 里还有手册，以及用大白话解释的命令清单。',
    'f2.q': '如果我关掉 App 或者断网呢？',
    'f2.a': '没关系。Claude 跑在你的服务器上，不在手机上。你可以关掉 App、进隧道、关机：回来时，对话和工作都还在原来的地方。',
    'f3.q': '我的项目存在哪里？',
    'f3.a': '存在你自己名下的服务器上，并在你的 GitHub 账号里留有备份。我们不保存你的任何东西：我们只负责安装，钥匙留在你手里。',
    'f4.q': '开始需要准备什么？',
    'f4.a': '三个账号：Anthropic 的付费订阅（Pro、Max、Team 或 Enterprise，Pro 就够）、一个免费的 GitHub 账号，以及一台带域名的小服务器。选完整安装的话，我们替你搞定。',
    'f5.q': '支持哪些 Claude 套餐？',
    'f5.a': '四个付费套餐都支持：Pro、Max、Team 和 Enterprise。它们跑的是同一个 Claude Code，区别只在用量额度。入门用 Pro 就够。',
    'cierre.h2a': '你的服务器。你的代码。', 'cierre.h2b': '你的口袋。',
    'cierre.p': '告诉我们你想搭什么，我们告诉你需要哪些东西，不收费也不绑定。',
    'cierre.cta': '联系我们',
    'pie.nota': 'Claude 与 Claude Code 是 Anthropic 的商标。本产品负责在你自己的服务器上安装和管理 Claude Code。'
  }

};
